export const FORUM_HIGHLIGHTS = [
    {
        id: 1,
        topic: "What are your go-to methods for soil moisture testing?",
        category: "Precision Agriculture",
        author: "Dr. Eleanor Vance",
        authorAvatar: "/images/avatars/eleanor-vance.jpg",
        replies: 42,
        lastReply: "3 hours ago",
        isTrending: true,
    },
    {
        id: 2,
        topic: "Best crop choices for vertical farming setups?",
        category: "Urban Farming",
        author: "Marco Diaz",
        authorAvatar: "/images/avatars/marco-diaz.jpg",
        replies: 28,
        lastReply: "1 day ago",
        isTrending: false,
    },
    {
        id: 3,
        topic: "The ROI of drone-based pesticide spraying: A case study",
        category: "Agri-Tech",
        author: "Chen Liang",
        authorAvatar: "/images/avatars/chen-liang.jpg",
        replies: 65,
        lastReply: "5 hours ago",
        isTrending: true,
    },
    {
        id: 4,
        topic: "Organic vs. Synthetic Fertilizers: A Heated Debate",
        category: "Sustainable Practices",
        author: "Sarah Jenkins",
        authorAvatar: "/images/avatars/sarah-jenkins.jpg",
        replies: 112,
        lastReply: "2 days ago",
        isTrending: false,
    },
    {
        id: 5,
        topic: "DIY automated irrigation systems for small-scale farms",
        category: "DIY & Innovation",
        author: "Tom Howard",
        authorAvatar: "/images/avatars/tom-howard.jpg",
        replies: 76,
        lastReply: "8 hours ago",
        isTrending: true,
    },
];

export const FEATURED_MEMBERS = [
    {
        id: 1,
        name: "Dr. Eleanor Vance",
        title: "Soil Scientist",
        avatar: "/images/avatars/eleanor-vance.jpg",
        contributions: 134,
        specialty: "Soil Health",
    },
    {
        id: 2,
        name: "Chen Liang",
        title: "Agri-Tech Entrepreneur",
        avatar: "/images/avatars/chen-liang.jpg",
        contributions: 98,
        specialty: "Drones & AI",
    },
    {
        id: 3,
        name: "Sarah Jenkins",
        title: "Organic Farmer",
        avatar: "/images/avatars/sarah-jenkins.jpg",
        contributions: 210,
        specialty: "Sustainable Farming",
    },
    {
        id: 4,
        name: "Marco Diaz",
        title: "Vertical Farming Specialist",
        avatar: "/images/avatars/marco-diaz.jpg",
        contributions: 75,
        specialty: "Urban Agriculture",
    },
];