export enum View {
  KNOWLEDGE = 'KNOWLEDGE',
  FUTURE_VISION = 'FUTURE_VISION',
  NETWORK_INPUT_HUB = 'NETWORK_INPUT_HUB',
  COMMUNITY = 'COMMUNITY',
  CARBON_LEDGER = 'CARBON_LEDGER',
  SAFE_HARVEST = 'SAFE_HARVEST',
  ROADMAP_AI = 'ROADMAP_AI',
  SCALEUP_SUMMIT = 'SCALEUP_SUMMIT',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  TRADEMARKS = 'TRADEMARKS',
  COMMUNITY_GUIDELINES = 'COMMUNITY_GUIDELINES',
  HOME = 'HOME',
  DASHBOARD = 'DASHBOARD',
  SUSTAINABILITY_FRAMEWORK = 'SUSTAINABILITY_FRAMEWORK',
  CROP_DOCTOR = 'CROP_DOCTOR',
  FARM_SCOUT = 'FARM_SCOUT',
  SMART_FARM_VR = 'SMART_FARM_VR',
  SERVICES = 'SERVICES',
  FINANCE = 'FINANCE',
  INVESTOR_PORTAL = 'INVESTOR_PORTAL',
  BRANDS = 'BRANDS',
  TRANSMISSION_GATEWAY = 'TRANSMISSION_GATEWAY',
  PROFESSIONAL = 'PROFESSIONAL',
  RESILIENCE = 'RESILIENCE',
  FIVE_THRUSTS = 'FIVE_THRUSTS',
}

export interface AgBizWeeklyReport {
  id: string;
  title: string;
  date: string;
  image: string;
  desc: string;
  type: string;
}
