export enum View {
  HOME = 'HOME',
  DASHBOARD = 'DASHBOARD',
  IMPACT_DASHBOARD = 'IMPACT_DASHBOARD',
  PLANET_WATCH = 'PLANET_WATCH',
  SAFE_HARVEST = 'SAFE_HARVEST',
  SUSTAINABILITY_FRAMEWORK = 'SUSTAINABILITY_FRAMEWORK',
  CARBON_LEDGER = 'CARBON_LEDGER',
  GREEN_LENS = 'GREEN_LENS',
  NUTRILIFE = 'NUTRILIFE',
  AGBIZ = 'AGBIZ',
  AGBIZ_WEEKLY = 'AGBIZ_WEEKLY',
  FINANCE = 'FINANCE',
  INVESTOR_PORTAL = 'INVESTOR_PORTAL',
  SUPPLY_CHAIN_AUDIT = 'SUPPLY_CHAIN_AUDIT',
  COMMUNITY = 'COMMUNITY',
  HERITAGE_FORUM = 'HERITAGE_FORUM',
  PEOPLE_AND_CULTURE = 'PEOPLE_AND_CULTURE',
  SCALEUP_SUMMIT = 'SCALEUP_SUMMIT',
  AI_ADVISOR = 'AI_ADVISOR',
  CROP_DOCTOR = 'CROP_DOCTOR',
  FARM_SCOUT = 'FARM_SCOUT',
  SMART_FARM_VR = 'SMART_FARM_VR',
  ROADMAP_AI = 'ROADMAP_AI',
  SIX_SIGMA_RCA = 'SIX_SIGMA_RCA',
  AI_CONSULTANT_FLOATING = 'AI_CONSULTANT_FLOATING',
  DATA_REGISTRY = 'DATA_REGISTRY',
  OUR_STORY = 'OUR_STORY',
  COMMUNITY_GUIDELINES = 'COMMUNITY_GUIDELINES',
  TRADEMARKS = 'TRADEMARKS',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  KNOWLEDGE = 'KNOWLEDGE',
  FUTURE_VISION = 'FUTURE_VISION',
  NETWORK_INPUT_HUB = 'NETWORK_INPUT_HUB',
  SERVICES = 'SERVICES',
  BRANDS = 'BRANDS',
  TRANSMISSION_GATEWAY = 'TRANSMISSION_GATEWAY',
  PROFESSIONAL = 'PROFESSIONAL',
  RESILIENCE = 'RESILIENCE',
  FIVE_THRUSTS = 'FIVE_THRUSTS',
  PROFILE = 'PROFILE',
  INFORMATION = 'INFORMATION',
  PRODUCTS = 'PRODUCTS',
  CART = 'CART',
  DATABASE = 'DATABASE',
  PEOPLE_AND_CULTURE_CLOUD = 'PEOPLE_AND_CULTURE_CLOUD',
  SUSTAINABILITY_CALCULATOR = 'SUSTAINABILITY_CALCULATOR',
  SIGN_UP = 'SIGN_UP',
  MEDIA = 'MEDIA',
  SUPPLY = 'SUPPLY',
  CUSTOMER = 'CUSTOMER',
  PARTNERSHIPS = 'PARTNERSHIPS',
  PODCAST = 'PODCAST',
  WEBINAR = 'WEBINAR',
  LIVE_HOST = 'LIVE_HOST',
  INTRANET_DASHBOARD = 'INTRANET_DASHBOARD',
  EXTRANET_DASHBOARD = 'EXTRANET_DASHBOARD',
  FRAMEWORK_DISTINCTIONS = 'FRAMEWORK_DISTINCTIONS',
  PORTFOLIO = 'PORTFOLIO'
}

export interface User {
  name: string;
  email: string;
  avatar?: string;
  role: string;
  esin?: string;
  eacBalance?: number;
}

export interface AgBizWeeklyReport {
  id: string;
  title: string;
  date: string;
  image: string;
  desc: string;
  type: string;
}
