export enum View {
  AUTH = "AUTH",
  HOME = "HOME",
  DASHBOARD = "DASHBOARD",
  IMPACT_DASHBOARD = "IMPACT_DASHBOARD",
  CROP_DOCTOR = "CROP_DOCTOR",
  FARM_SCOUT = "FARM_SCOUT",
  SMART_FARM_VR = "SMART_FARM_VR",
  SAFE_HARVEST = "SAFE_HARVEST",
  PROFILE = "PROFILE",
  PLANET_WATCH = "PLANET_WATCH",
  SUSTAINABILITY_FRAMEWORK = "SUSTAINABILITY_FRAMEWORK",
  CARBON_LEDGER = "CARBON_LEDGER",
  GREEN_LENS = "GREEN_LENS",
  NUTRILIFE = "NUTRILIFE",
  AGBIZ = "AGBIZ",
  AGBIZ_WEEKLY = "AGBIZ_WEEKLY",
  FINANCE = "FINANCE",
  INVESTOR_PORTAL = "INVESTOR_PORTAL",
  SUPPLY_CHAIN_AUDIT = "SUPPLY_CHAIN_AUDIT",
  COMMUNITY = "COMMUNITY",
  HERITAGE_FORUM = "HERITAGE_FORUM",
  SCALEUP_SUMMIT = "SCALEUP_SUMMIT",
  AI_ADVISOR = "AI_ADVISOR",
  ROADMAP_AI = "ROADMAP_AI",
  SIX_SIGMA_RCA = "SIX_SIGMA_RCA",
  AI_CONSULTANT_FLOATING = "AI_CONSULTANT_FLOATING",
  COMMUNITY_GUIDELINES = "COMMUNITY_GUIDELINES",
  TRADEMARKS = "TRADEMARKS",
  PRIVACY_POLICY = "PRIVACY_POLICY",
  BRANDS = "BRANDS",
  DATA_REGISTRY = "DATA_REGISTRY",
  NETWORK_INPUT_HUB = "NETWORK_INPUT_HUB",
  ABOUT = "ABOUT",
  KNOWLEDGE = "KNOWLEDGE",
  FUTURE_VISION = "FUTURE_VISION",
  SERVICES = "SERVICES",
  TRANSMISSION_GATEWAY = "TRANSMISSION_GATEWAY",
  PROFESSIONAL = "PROFESSIONAL",
  RESILIENCE = "RESILIENCE",
  FIVE_THRUSTS = "FIVE_THRUSTS",
  INFORMATION = "INFORMATION",
  PRODUCTS = "PRODUCTS",
  PRODUCT_DETAIL = "PRODUCT_DETAIL",
  CART = "CART",
  DATABASE = "DATABASE",
  SUSTAINABILITY_CALCULATOR = "SUSTAINABILITY_CALCULATOR",
  MEDIA = "MEDIA",
  SUPPLY = "SUPPLY",
  CUSTOMER = "CUSTOMER",
  CUSTOMER_DETAIL = "CUSTOMER_DETAIL",
  PARTNERSHIPS = "PARTNERSHIPS",
  PODCAST = "PODCAST",
  WEBINAR = "WEBINAR",
  LIVE_HOST = "LIVE_HOST",
  INTRANET_DASHBOARD = "INTRANET_DASHBOARD",
  EXTRANET_DASHBOARD = "EXTRANET_DASHBOARD",
  FRAMEWORK_DISTINCTIONS = "FRAMEWORK_DISTINCTIONS",
  PORTFOLIO = "PORTFOLIO",
  AI_CHAT = "AI_CHAT",
  COMMUNITY_GARDEN = "COMMUNITY_GARDEN",
  DESIGN_SYSTEM = "DESIGN_SYSTEM",
  GROUP_LOGIN = "GROUP_LOGIN",
  ORGANIZATION_LOGIN = "ORGANIZATION_LOGIN"
}

export interface User {
  uid: string;
  name: string;
  email: string;
  role: 'Farmer' | 'Researcher' | 'Stakeholder' | 'Other' | 'user';
  avatar?: string;
  joinedDate?: string;
  esin?: string;
  eacBalance?: number;
  isVerified?: boolean;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  price: string;
  rating: number;
  image: string;
  thrust: string;
  category: string;
  type: 'PHYSICAL' | 'DIGITAL';
  features?: string[];
  impact?: string;
  duration?: string;
  instructor?: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}

export interface Report {
  title: string;
  author: string;
  date: string;
  tags: string[];
  content: string;
}
