import { SearchResult } from './types';

export const sampleData: SearchResult[] = [
  {
    id: 1,
    title: 'Advanced AI for Crop Disease Diagnosis',
    summary: 'Leveraging convolutional neural networks to identify common crop diseases with over 98% accuracy from leaf images.',
    category: 'AI & Machine Learning',
    date: '2023-10-15',
    url: '#',
    author: 'Dr. Alisha Gupta',
    source: 'Journal of Agricultural AI',
  },
  {
    id: 2,
    title: 'The Comprehensive Guide to Soil Health Management',
    summary: 'A deep dive into maintaining soil fertility, structure, and biodiversity for long-term sustainable agriculture.',
    category: 'Soil Science',
    date: '2023-09-22',
    url: '#',
    author: 'Dr. Marcus Grant',
    source: 'Sustainable Farming Institute',
  },
  {
    id: 3,
    title: 'Breakthroughs in Drought-Resistant Crop Varieties',
    summary: 'Exploring the latest CRISPR-edited gene sequences that significantly improve water retention in corn and wheat.',
    category: 'Crop Science',
    date: '2023-11-01',
    url: '#',
    author: 'Dr. Lena Petrova',
    source: 'Genomic Agriculture Today',
  },
  {
    id: 4,
    title: 'Understanding the Agricultural Carbon Credit Market',
    summary: 'A practical guide for farmers on how to monetize carbon sequestration through regenerative farming practices.',
    category: 'Finance & Economics',
    date: '2023-10-28',
    url: '#',
    author: 'Johnathan Bauer',
    source: 'AgriFinance Monthly',
  },
  {
    id: 5,
    title: 'Precision Irrigation Techniques for Water Conservation',
    summary: 'Utilizing IoT sensors and automated drip systems to reduce water usage by up to 40% without impacting yield.',
    category: 'Technology & Equipment',
    date: '2023-09-05',
    url: '#',
    author: 'Maria Hernandez',
    source: 'Smart Agriculture Journal',
  },
  {
    id: 6,
    title: 'AI-Powered Predictive Analytics for Harvest Timing',
    summary: 'This paper covers a new model that uses weather data, satellite imagery, and soil moisture to predict optimal harvest windows.',
    category: 'AI & Machine Learning',
    date: '2023-11-10',
    url: '#',
    author: 'Dr. Kenji Tanaka',
    source: 'International Symposium on AgTech',
  },
  {
    id: 7,
    title: 'The Role of Mycorrhizal Fungi in Nutrient Uptake',
    summary: 'An examination of how symbiotic fungal networks can be harnessed to improve phosphorus and nitrogen uptake in crops.',
    category: 'Soil Science',
    date: '2023-08-19',
    url: '#',
    author: 'Dr. Fatima Ahmed',
    source: 'Applied Soil Ecology',
  },
  {
    id: 8,
    title: 'Post-Harvest Loss Reduction through Smart Storage',
    summary: 'Implementing sensor-based monitoring systems in grain silos to control temperature, humidity, and pests, reducing spoilage.',
    category: 'Technology & Equipment',
    date: '2023-07-30',
    url: '#',
    author: 'David Wilson',
    source: 'Global Food Security Initiative',
  },
];
