export const REWARDS = {
  AUTHENTICATION: {
    VERIFIED_REGISTRATION: 50,
    ORG_GROUP_VERIFICATION: 500,
  },
  CONTRIBUTION: {
    POST_UPDATE: 5,
    UPLOAD_MEETING_MINUTES: 20,
    UPLOAD_PODCAST_AUDIO: 30,
    UPLOAD_DEFAULT: 5,
    RECEIVE_LIKE: 2,
  },
  EDUCATION: {
    COMPLETE_TUTORIAL: 100,
    PASS_SKILL_QUIZ: 50,
  },
  INDUSTRIAL: {
    COMPLETE_WORKER_PROFILE: 200,
    GET_HIRED: 1000,
  },
};

export const FREQUENCY_CAPS = {
  CONTRIBUTION: {
    POST_UPDATE: 5, // per day
    UPLOAD_HIGH_VALUE_FILE: 3, // per day
  },
};
