
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVYoqxPepnbRRtC68BRTxgqFp1FVO3xI',
    appId: '1:399076515746:web:f947e5e4dd216826b81cfb',
    messagingSenderId: '399076515746',
    projectId: 'envirosagro-git-93534258-78537',
    authDomain: 'envirosagro-git-93534258-78537.firebaseapp.com',
    storageBucket: 'envirosagro-git-93534258-78537.appspot.com',
    measurementId: 'G-1MNDXE8PG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVYoqxPepnbRRtC68BRTxgqFp1FVO3xI',
    appId: '1:399076515746:android:f947e5e4dd216826b81cfb',
    messagingSenderId: '399076515746',
    projectId: 'envirosagro-git-93534258-78537',
    storageBucket: 'envirosagro-git-93534258-78537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVYoqxPepnbRRtC68BRTxgqFp1FVO3xI',
    appId: '1:399076515746:ios:f947e5e4dd216826b81cfb',
    messagingSenderId: '399076515746',
    projectId: 'envirosagro-git-93534258-78537',
    storageBucket: 'envirosagro-git-93534258-78537.appspot.com',
    iosBundleId: 'com.example.envirosagro',
  );

    static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVYoqxPepnbRRtC68BRTxgqFp1FVO3xI',
    appId: '1:399076515746:ios:f947e5e4dd216826b81cfb',
    messagingSenderId: '399076515746',
    projectId: 'envirosagro-git-93534258-78537',
    storageBucket: 'envirosagro-git-93534258-78537.appspot.com',
    iosBundleId: 'com.example.envirosagro',
  );
}
